#### FlipRoboTechnology | Batch-- DS2301

# WEB SCRAPING ASSIGNMENT SET 4 | Selenium Exception Handling

#### Read all the problem statements, notes carefully and scrape the required data using any web scraping tool of your choice.
• You have to handle commonly occurring EXCEPTIONS by using exception handling programing. To get 
information about selenium Exceptions. You may visit following links:
1. https://selenium-python.readthedocs.io/api.html
2. https://www.guru99.com/exception-handling-selenium.html
3. https://stackoverflow.com/questions/38022658/selenium-python-handling-no-such-elementexception/38023345

In [2]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\nehas\anaconda3\lib\site-packages (4.8.0)
Requirement already satisfied: trio~=0.17 in c:\users\nehas\anaconda3\lib\site-packages (from selenium) (0.22.0)
Requirement already satisfied: urllib3[socks]~=1.26 in c:\users\nehas\anaconda3\lib\site-packages (from selenium) (1.26.9)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\nehas\anaconda3\lib\site-packages (from selenium) (2021.10.8)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\nehas\anaconda3\lib\site-packages (from selenium) (0.9.2)
Requirement already satisfied: async-generator>=1.9 in c:\users\nehas\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: idna in c:\users\nehas\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: sortedcontainers in c:\users\nehas\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in c:\users\nehas\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.1.0)
Requirement already satisfied: outcome in c:\users\nehas\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: attrs>=19.2.0 in c:\users\nehas\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: sniffio in c:\users\nehas\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: cffi>=1.14 in c:\users\nehas\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.0)
Requirement already satisfied: pycparser in c:\users\nehas\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: wsproto>=0.14 in c:\users\nehas\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\nehas\anaconda3\lib\site-packages (from urllib3[socks]~=1.26->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\nehas\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

# Q1. Scrape the details of most viewed videos on YouTube from Wikipedia.

Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos
You need to find following details:

A) Rank

B) Name

C) Artist

D) Upload date

E) Views

#### Importing necessary libraries

In [1]:
import selenium                      #importing libraries that is used to work with selenium.
from selenium import webdriver       #importing webdriver module from slenium to open automated chrome window .
from selenium.webdriver.common.by import By    # importing inbulit class by.

from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

from selenium.common.exceptions import NoSuchElementException 
from selenium.common.exceptions import StaleElementReferenceException

from bs4 import BeautifulSoup
import requests

import pandas as pd     # to create a dataframe 
import time

import warnings         # Importing any sort of warnings.
warnings.filterwarnings('ignore')

#### 1) Getting the webpage Url( https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos )

In [23]:
Url = 'https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos'

In [24]:
driver=webdriver.Chrome(r"C:\Users\nehas\chromedriver.exe") # Connect to the driver.
driver.maximize_window()
driver.get(Url)
time.sleep(2)

#### 2) Make a Empty List of all the data to be scraped.

In [25]:
rank         = []
name         = []
artist       = []
upload_date  = []
views        = []

#### 3) Start scraping data using the given URL.

In [26]:
# Extracting Rank Via X path
try:
    rnk=driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td[1]")
    for i in rnk:
        rank.append(i.text)
except NoSuchElementException as e:
    rank.append("EXCEPTION RAISED")
except StaleElementReferenceException:
    rank.append("EXCEPTION RAISED")
    
 # Extracting Name Via X path
try:
    nme=driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td[2]")
    for i in nme:
        name.append(i.text)
except NoSuchElementException as e:
    name.append("EXCEPTION RAISED")
except StaleElementReferenceException:
    name.append("EXCEPTION RAISED")
    
# Extracting Artist Name Via Xpath
try:
    artst=driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td[3]")
    for i in artst:
        artist.append(i.text)
except NoSuchElementException as e:
    artist.append("EXCEPTION RAISED")
except StaleElementReferenceException:
    artist.append("EXCEPTION RAISED") 
    
# Extracting Upload date Via Xpath
try:
    upload=driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td[5]")
    for i in upload:
        upload_date.append(i.text)
except NoSuchElementException as e:
    upload_date.append("EXCEPTION RAISED")
except StaleElementReferenceException:
    upload_date.append("EXCEPTION RAISED") 
    
# Extracting Views via Xpath
try:
    viw=driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td[4]")
    for i in viw:
        views.append(i.text)
except NoSuchElementException as e:
    views.append("EXCEPTION RAISED")
except StaleElementReferenceException:
    views.append("EXCEPTION RAISED")

#### 4)Check the length of each:

In [27]:
len(rank),len(name),len(upload_date),len(artist),len(views)

(49, 49, 49, 49, 49)

#### 5) Create a Dataframe for scrap data

In [28]:
Wiki_YTvideos=pd.DataFrame({'Rank':rank,'Video Name':name,'Uploader':artist,'Views (in Billons)':views,'Upload Date':upload_date})

print('\033[1m'+'Most Viewed Video on YouTube from Wikipedia :'+'\033[0m')

Wiki_YTvideos[:30]

Most Viewed Video on YouTube from Wikipedia :

,Rank,Video Name,Uploader,Views (in Billons),Upload Date
0,1.,"""Baby Shark Dance""[4]",Pinkfong Baby Shark - Kids' Songs & Stories,12.37,"June 17, 2016"
1,2.,"""Despacito""[7]",Luis Fonsi,8.09,"January 12, 2017"
2,3.,"""Johny Johny Yes Papa""[14]",LooLoo Kids,6.63,"October 8, 2016"
3,4.,"""Bath Song""[15]",Cocomelon – Nursery Rhymes,6.03,"May 2, 2018"
4,5.,"""Shape of You""[16]",Ed Sheeran,5.92,"January 30, 2017"
5,6.,"""See You Again""[18]",Wiz Khalifa,5.79,"April 6, 2015"
6,7.,"""Phonics Song with Two Words""[23]",ChuChu TV,5.17,"March 6, 2014"
7,8.,"""Wheels on the Bus""[24]",Cocomelon – Nursery Rhymes,4.95,"May 24, 2018"
8,9.,"""Uptown Funk""[25]",Mark Ronson,4.84,"November 19, 2014"
9,10.,"""Learning Colors – Colorful Eggs on a Farm""[26]",Miroshka TV,4.83,"February 27, 2018"
10,11.,"""Gangnam Style""[27]",Psy,4.70,"July 15, 2012"
11,12.,"""Masha and the Bear – Recipe for Disaster""[32]",Get Movies,4.53,"January 31, 2012"
12,13.,"""Dame Tu Cosita""[33]",El Chombo,4.24,"April 5, 2018"
13,14.,"""Sugar""[34]",Maroon 5,3.82,"January 14, 2015"
14,15.,"""Axel F""[35]",Crazy Frog,3.76,"June 16, 2009"
15,16.,"""Roar""[36]",Katy Perry,3.73,"September 5, 2013"
16,17.,"""Counting Stars""[37]",OneRepublic,3.73,"May 31, 2013"
17,18.,"""Sorry""[38]",Justin Bieber,3.63,"October 22, 2015"
18,19.,"""Thinking Out Loud""[39]",Ed Sheeran,3.55,"October 7, 2014"
19,20.,"""Baa Baa Black Sheep""[40]",Cocomelon – Nursery Rhymes,3.51,"June 25, 2018"
20,21.,"""Waka Waka (This Time for Africa)""[41]",Shakira,3.48,"June 4, 2010"
21,22.,"""Dark Horse""[42]",Katy Perry,3.45,"February 20, 2014"
22,23.,"""Faded""[43]",Alan Walker,3.41,"December 3, 2015"
23,24.,"""Let Her Go""[44]",Passenger,3.38,"July 25, 2012"
24,25.,"""Girls Like You""[45]",Maroon 5,3.37,"May 31, 2018"
25,26.,"""Perfect""[46]",Ed Sheeran,3.37,"November 9, 2017"
26,27.,"""Bailando""[47]",Enrique Iglesias,3.34,"April 11, 2014"
27,28.,"""Lean On""[48]",Major Lazer,3.33,"March 22, 2015"
28,29.,"""Lakdi Ki Kathi""[49]",Jingle Toons,3.32,"June 14, 2018"
29,30.,"""Humpty the train on a fruits ride""[50]",Kiddiestv Hindi – Nursery Rhymes & Kids Songs,3.31,"January 26, 2018"

In [29]:
driver.close()

## Q2. Scrape the details team India’s international fixtures from bcci.tv. 

Url = https://www.bcci.tv/.  You need to find following details:

A) Match title (I.e. 1st ODI)

B) Series

C) Place

D) Date

E) Time

Note: - From bcci.tv home page you have reach to the international fixture page through code

#### 1) Getting the webpage Url(https://www.bcci.tv/)

In [69]:
url = 'https://www.bcci.tv/'

In [70]:
driver=webdriver.Chrome(r"C:\Users\nehas\chromedriver.exe")            # Connect to the driver.
driver.maximize_window()
driver.get(url)

#### 2) Opening International fixtures webpage through browser.

In [71]:
try:
    inter_tag=driver.find_element(By.XPATH,'/html/body/nav/div[1]/div[2]/ul[1]/li[2]/a')
    inter_tag.click()
except NoSuchElementException as e:
    driver.get(inter_tag.get_attribute('href'))

In [72]:
fix_url=[]

link=driver.find_elements(By.XPATH,'//a[@class="match-btn match-card-btn ng-scope"]')
for i in link:
    fix_url.append(i.get_attribute('href'))

In [73]:
len(fix_url)

3

#### 3) Make a Empty List of all the data to be scraped.

In [74]:
match   =  []
series  =  []
place   =  []
date    =  []
time    =  []

#### 4) Start scraping data using the given URL.

In [75]:

# Extracting match Via X path
try:
    mtch=driver.find_elements(By.XPATH,'//span[@class="matchOrderText ng-binding ng-scope"]')
    for i in mtch:
        match.append(i.text)
except NoSuchElementException as e:
    match.append("EXCEPTION RAISED")

    
 # Extracting match Series Via X path
try:
    ser=driver.find_elements(By.XPATH,'//div[@class="match-card-top"]/h5')
    for i in ser:
        series.append(i.text)
except NoSuchElementException as e:
    series.append("EXCEPTION RAISED")

    
# Extracting Place Name Via Xpath
try:
    plc=driver.find_elements(By.XPATH,'//div[@class="match-place ng-scope" ]/span[2]')
    for i in plc:
        place.append(i.text)
except NoSuchElementException as e:
    place.append("EXCEPTION RAISED")
 
    
# Extracting Date Via Xpath
try:
    dte=driver.find_elements(By.XPATH,'//div[@class="match-dates ng-binding"]')
    for i in dte:
        date.append(i.text)
except NoSuchElementException as e:
    date.append("EXCEPTION RAISED")
    
    
# Extracting Time via Xpath
try:
    t=driver.find_elements(By.XPATH,'//div[@class="match-info"]/div[2]')
    for i in t:
        time.append(i.text)
except NoSuchElementException as e:
    time.append("EXCEPTION RAISED")

In [76]:
len(match),len(place),len(series),len(date),len(time)

(3, 3, 3, 3, 3)

In [77]:

bcci_cricket=pd.DataFrame({'Match Title':match,'Tournament':series,'Venue':place,'Date':date,'Time':time})

print('\033[1m'+'Team India’s Upcoming International fixtures :'+'\033[0m')

bcci_cricket[:3]

Team India’s Upcoming International fixtures :

,Match Title,Tournament,Venue,Date,Time
0,1st ODI -,AUSTRALIA TOUR OF INDIA 2023,"Wankhede Stadium,",17 MAR 2023,1:30 PM IST
1,2nd ODI -,AUSTRALIA TOUR OF INDIA 2023,"Dr YS Rajasekhara Reddy ACA-VDCA Cricket Stadium,",19 MAR 2023,1:30 PM IST
2,3rd ODI -,AUSTRALIA TOUR OF INDIA 2023,"MA Chidambaram Stadium,",22 MAR 2023,1:30 PM IST

In [78]:
driver.close()

## Q3. Scrape the details of State-wise GDP of India from statistics time.com. 
Url = http://statisticstimes.com/
You have to find following details:

A) Rank

B) State

C) GSDP(18-19)- at current prices

D) GSDP(19-20)- at current prices

E) Share(18-19)

F) GDP($ billion)

Note: - From statistics times home page you have to reach to economy page through code.

#### 1)Getting the webpage Url(http://statisticstimes.com/)
Connect to the driver.

In [49]:
driver=webdriver.Chrome(r"C:\Users\nehas\chromedriver.exe")            
driver.maximize_window()
driver.get(' http://statisticstimes.com/')

In [50]:
# Clicking on Economy section-

tag=driver.find_element(By.XPATH,'/html/body/div[2]/div[1]/div[2]/div[2]/button')
tag.click()

In [51]:
#Selecting and clicking on India tag

india_tag=driver.find_element(By.XPATH,'//div[@class="dropdown-content"]/a[3]')
india_tag.click()

In [52]:
# Clicking Indian State GDP-

indi_state=driver.find_element(By.XPATH,'//ul[@style="list-style-type:none;margin-left:20px;"]/li[1]/a')
try:
    indi_state.click()
except NoSuchElementException as e:
    driver.get(indi_state.get_attribute('href'))

#### 2) Make a Empty List of all the data to be scraped.

In [53]:
rnk         = []
state       = []
GSDP_18_19  = []
GSDP_19_20  = []
share       = []
GDP         = []

#### 3) Start scraping data using the given URL.

In [54]:
# Extracting Rank via Xpath
try:
    rank=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[1]')
    for i in rank:
        rnk.append(i.text)
except NoSuchElementException as e:
    rnk.append('_')
    
# Extracting State via Xpath--
try:
    ste=driver.find_elements(By.XPATH,'//table[@id="table_id" ]/tbody/tr/td[2]')
    for i in ste:
        state.append(i.text)
except NoSuchElementException as e:
    state.append('_')
    
    
# Extracting GSDP_18_19 via Xpath--
try:
    GSDP=driver.find_elements(By.XPATH,'//table[@id="table_id" ]/tbody/tr/td[4]')
    for i in GSDP:
        GSDP_18_19.append(i.text)
except NoSuchElementException as e:
    GSDP_18_19.append('_')
        
# Extracting GSDP_19_20 via Xpath--
try:
    GSD=driver.find_elements(By.XPATH,'//table[@id="table_id" ]/tbody/tr/td[3]')
    for i in GSD:
        GSDP_19_20.append(i.text)
except NoSuchElementException as e:
    GSDP_19_20.append('_')
    
# Extracting share via Xpath--
try:
    shr=driver.find_elements(By.XPATH,'//table[@id="table_id" ]/tbody/tr/td[5]')
    for i in shr:
        share.append(i.text)
except NoSuchElementException as e:
    share.append('_')
        
# Extracting GDP via Xpath--
try:
    G=driver.find_elements(By.XPATH,'//table[@id="table_id" ]/tbody/tr/td[6]')
    for i in G:
        GDP.append(i.text)
except NoSuchElementException as e:
    GDP.append('_')

#### 4)Check the length of each:

In [55]:
len(rnk),len(state),len(GSDP_18_19 ),len(GSDP_19_20),len(share),len(GDP)

(33, 33, 33, 33, 33, 33)

#### 5)Creating a Dataframe-

In [58]:
StateGDP=pd.DataFrame({'Rank':rnk,'State':state,'GDSP 18-19':GSDP_18_19,'GDSP 19-20':GSDP_19_20,
                            'Share':share,'GDP (in Billions)':GDP})

print('\033[1m'+'State-wise GDP of India :'+'\033[0m')

StateGDP

State-wise GDP of India :

,Rank,State,GDSP 18-19,GDSP 19-20,Share,GDP (in Billions)
0,1,Maharashtra,"2,632,792",-,13.94%,399.921
1,2,Tamil Nadu,"1,630,208","1,845,853",8.63%,247.629
2,3,Uttar Pradesh,"1,584,764","1,687,818",8.39%,240.726
3,4,Gujarat,"1,502,899",-,7.96%,228.290
4,5,Karnataka,"1,493,127","1,631,977",7.91%,226.806
5,6,West Bengal,"1,089,898","1,253,832",5.77%,165.556
6,7,Rajasthan,"942,586","1,020,989",4.99%,143.179
7,8,Andhra Pradesh,"862,957","972,782",4.57%,131.083
8,9,Telangana,"861,031","969,604",4.56%,130.791
9,10,Madhya Pradesh,"809,592","906,672",4.29%,122.977
10,11,Kerala,"781,653",-,4.14%,118.733
11,12,Delhi,"774,870","856,112",4.10%,117.703
12,13,Haryana,"734,163","831,610",3.89%,111.519
13,14,Bihar,"530,363","611,804",2.81%,80.562
14,15,Punjab,"526,376","574,760",2.79%,79.957
15,16,Odisha,"487,805","521,275",2.58%,74.098
16,17,Assam,"315,881",-,1.67%,47.982
17,18,Chhattisgarh,"304,063","329,180",1.61%,46.187
18,19,Jharkhand,"297,204","328,598",1.57%,45.145
19,20,Uttarakhand,"245,895",-,1.30%,37.351
20,21,Jammu & Kashmir,"155,956",-,0.83%,23.690
21,22,Himachal Pradesh,"153,845","165,472",0.81%,23.369
22,23,Goa,"73,170","80,449",0.39%,11.115
23,24,Tripura,"49,845","55,984",0.26%,7.571
24,25,Chandigarh,"42,114",-,0.22%,6.397
25,26,Puducherry,"34,433","38,253",0.18%,5.230
26,27,Meghalaya,"33,481","36,572",0.18%,5.086
27,28,Sikkim,"28,723","32,496",0.15%,4.363
28,29,Manipur,"27,870","31,790",0.15%,4.233
29,30,Nagaland,"27,283",-,0.14%,4.144
30,31,Arunachal Pradesh,"24,603",-,0.13%,3.737
31,32,Mizoram,"22,287","26,503",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

In [59]:
driver.close()

## Q4. Scrape the details of trending repositories on Github.com. 

Url = https://github.com/  .
You have to find the following details:
    
A) Repository title

B) Repository description

C) Contributors count

D) Language used

Note: - From the home page you have to click on the trending option from Explore menu through code.

#### 1)Getting the webpage Url( https://github.com/ )
Connect to the driver.

In [99]:
driver=webdriver.Chrome(r"C:\Users\nehas\chromedriver.exe")            
driver.maximize_window()
driver.get(' https://github.com/')

In [101]:
# Clicking on Open source section-

opensource_tag=driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/button')
opensource_tag.click()

In [102]:
# Clicking on trending option---
trending_tag=driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/div/ul[3]/li[3]/a')
trending_tag.click()

#### 2) Make a Empty List of all the data to be scraped.¶

In [103]:
rtitle         = []
rdescription   = []
ccount         = []
lang           = []

#### 3) Start scraping data using the given URL.

In [104]:
# scraping respository URL:
URL=[]
link=driver.find_elements(By.XPATH,'//h1[@class="h3 lh-condensed"]/a')
for i in link:
    URL.append(i.get_attribute('href'))

In [105]:
len(URL)

25

In [107]:
#Extracting Title name via Xpath--

title=driver.find_elements(By.XPATH,'//h1[@class="h3 lh-condensed"]/a') 
for i in title:
    try:
        rtitle.append(i.text)
    except NoSuchElementException as e:
        rtitle.append('_')

In [108]:
rtitle

['togethercomputer / OpenChatKit',
 'ggerganov / llama.cpp',
 'AstroNvim / AstroNvim',
 'exaloop / codon',
 'Azure-Samples / azure-search-openai-demo',
 'davinci1012 / pinduoduo_backdoor_unpacker',
 'Postcatlab / postcat',
 'Bin-Huang / chatbox',
 'midudev / openui.com',
 'base-org / node',
 'kaixindelele / ChatPaper',
 'whoiskatrin / sql-translator',
 'microsoft / visual-chatgpt',
 'chathub-dev / chathub',
 'Genymobile / scrcpy',
 'TheAlgorithms / Python',
 'ccfos / nightingale',
 'tangly1024 / NotionNext',
 'svc-develop-team / so-vits-svc',
 'EbookFoundation / free-programming-books',
 'GanymedeNil / document.ai',
 'oobabooga / text-generation-webui',
 'ggerganov / whisper.cpp',
 'pgrok / pgrok',
 'ggerganov / ggml']

In [109]:
# Extracting repository description,contributor count,language via Xpath--
for i in URL:
    driver.get(i)
    time.sleep(2)

    try:
        des=driver.find_element(By.XPATH,'/html/body/div[1]/div[4]/div/main/turbo-frame/div/div/div/div[2]/div[2]/div/div[1]/div/p')
        rdescription.append(des.text)
    except NoSuchElementException as e:
        rdescription.append('_')

    try:
        count=driver.find_element(By.XPATH,"//a[contains(@href,'contributors')]/span")
        ccount.append(count.text)
    except NoSuchElementException as e:
        ccount.append('_')
    
    try:
        lng=driver.find_element(By.XPATH,"//a[contains(@href,'search?')]/span[1]")
        lang.append(lng.text)
    except NoSuchElementException as e:
        lang.append('_')

In [110]:
rdescription

['_',
 "Port of Facebook's LLaMA model in C/C++",
 'AstroNvim is an aesthetic and feature-rich neovim config that is extensible and easy to use with a great set of plugins',
 'A high-performance, zero-overhead, extensible Python compiler using LLVM',
 'Demonstration of how to leverage Azure OpenAI and Cognitive Search to enable Information Search and Discovery over organizational content',
 'Samples and Unpacker of malicious backdoors and exploits developed and used by Pinduoduo',
 'Postcat 是一个可扩展的 API 工具平台。集合基础的 API 管理和测试功能，并且可以通过插件简化你的 API 开发工作，让你可以更快更好地创建 API。An extensible API tool.',
 'a cross-platform desktop client for OpenAI API, also a prompt debugging and management tool.',
 'Generador de componentes de UI con IA',
 'Everything required to run your own Base node',
 'Use ChatGPT to summarize the arXiv papers.',
 'SQL Translator is a tool for converting natural language queries into SQL code using artificial intelligence. This project is 100% free and open source.',
 'Official repo for the paper: Visual ChatGPT: Talking, Drawing and Editing with Visual Foundation Models',
 'All-in-one chatbot client',
 'Display and control your Android device',
 'All Algorithms implemented in Python',
 'An enterprise-level cloud-native monitoring system, which can be used as drop-in replacement of Prometheus for alerting and Grafana for visualization.',
 '一个使用 NextJS + Notion API 实现的，部署在 Vercel 上的静态博客系统。为Notion和所有创作者设计。',
 'SoftVC VITS Singing Voice Conversion',
 '📚 Freely available programming books',
 '基于向量数据库与GPT3.5的通用本地知识库方案(A universal local knowledge base solution based on vector database and GPT3.5)',
 'A gradio web UI for running Large Language Models like GPT-J 6B, OPT, GALACTICA, LLaMA, and Pygmalion.',
 "Port of OpenAI's Whisper model in C/C++",
 "Poor man's ngrok - a multi-tenant HTTP reverse tunnel solution through SSH remote port forwarding",
 'Tensor library for machine learning']

#### 4)Check the length of each:

In [111]:
len(rtitle),len(rdescription),len(ccount ),len(lang)

(25, 25, 25, 25)

#### 5)Creating a Dataframe-

In [112]:
Github=pd.DataFrame({'Title':rtitle,'Description':rdescription,'Contributors_count':ccount,'Language_used':lang})

print('\033[1m'+'GitHub Trending Repository :'+'\033[0m')

Github

GitHub Trending Repository :

,Title,Description,Contributors_count,Language_used
0,togethercomputer / OpenChatKit,_,7,Python
1,ggerganov / llama.cpp,Port of Facebook's LLaMA model in C/C++,16,C
2,AstroNvim / AstroNvim,AstroNvim is an aesthetic and feature-rich neo...,48,Lua
3,exaloop / codon,"A high-performance, zero-overhead, extensible ...",7,C++
4,Azure-Samples / azure-search-openai-demo,Demonstration of how to leverage Azure OpenAI ...,4,Python
5,davinci1012 / pinduoduo_backdoor_unpacker,Samples and Unpacker of malicious backdoors an...,2,Java
6,Postcatlab / postcat,Postcat 是一个可扩展的 API 工具平台。集合基础的 API 管理和测试功能，并且可...,12,JavaScript
7,Bin-Huang / chatbox,a cross-platform desktop client for OpenAI API...,_,TypeScript
8,midudev / openui.com,Generador de componentes de UI con IA,3,JavaScript
9,base-org / node,Everything required to run your own Base node,8,Shell
10,kaixindelele / ChatPaper,Use ChatGPT to summarize the arXiv papers.,4,Python
11,whoiskatrin / sql-translator,SQL Translator is a tool for converting natura...,5,TypeScript
12,microsoft / visual-chatgpt,Official repo for the paper: Visual ChatGPT: T...,9,Python
13,chathub-dev / chathub,All-in-one chatbot client,_,TypeScript
14,Genymobile / scrcpy,Display and control your Android device,108,C
15,TheAlgorithms / Python,All Algorithms implemented in Python,943,Python
16,ccfos / nightingale,An enterprise-level cloud-native monitoring sy...,92,Go
17,tangly1024 / NotionNext,一个使用 NextJS + Notion API 实现的，部署在 Vercel 上的静态博客...,21,JavaScript
18,svc-develop-team / so-vits-svc,SoftVC VITS Singing Voice Conversion,9,Python
19,EbookFoundation / free-programming-books,📚 Freely available programming books,"2,496",_
20,GanymedeNil / document.ai,基于向量数据库与GPT3.5的通用本地知识库方案(A universal local kno...,2,Python
21,oobabooga / text-generation-webui,A gradio web UI for running Large Language Mod...,23,Python
22,ggerganov / whisper.cpp,Port of OpenAI's Whisper model in C/C++,65,C
23,pgrok / pgrok,Poor man's ngrok - a multi-tenant HTTP reverse...,6,Go
24,ggerganov / ggml,Tensor library for machine learning,3,C

In [113]:
driver.close()

## Q5. Scrape the details of top 100 songs on billiboard.com. 

Url = https:/www.billboard.com/  .You have to find the following details:

A) Song name

B) Artist name

C) Last week rank

D) Peak rank

E) Weeks on board

Note: - From the home page you have to click on the charts option then hot 100-page link through code.

#### 1)Getting the webpage Url(https:/www.billboard.com/)¶
Connect to the driver.

In [32]:
driver=webdriver.Chrome(r"C:\Users\nehas\chromedriver.exe")            
driver.maximize_window()
driver.get(' https://billboard.com/')

In [33]:
# Clicking on Chart option via Xpath--

chart_tag=driver.find_element(By.XPATH,'/html/body/div[3]/header/div/div[2]/div/div/div[2]/div[2]/div/div/nav/ul/li[1]/a')
chart_tag.click()

In [35]:
# Clicking on View Chart option via Xpath--

view_tag=driver.find_element(By.XPATH,'/html/body/div[3]/main/div[2]/div[1]/div[1]/div/div/div[3]/a')
view_tag.click()

#### 2) Make a Empty List of all the data to be scraped.¶

In [36]:
song            = []
artist          = []
last_week_rank  = []
peak_rank       = []
weeks           = []

#### 3) Start scraping data using the given URL

In [37]:
sng=driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"] ')
for i in sng:
    try:
        song.append(i.text.split('\n')[1])
    except NoSuchElementException as e:
        song.append('_')

In [38]:
art=driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]')
for i in art:
    try:
        artist.append(i.text.split('\n')[2])
    except NoSuchElementException as e:
        artist.append('_')
        
lwr=driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]')
for i in lwr:
    try:
        last_week_rank.append(i.text.split('\n')[3])
    except NoSuchElementException as e:
        last_week_rank.append('_')
        
pr=driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]')
for i in pr:
    try:
        peak_rank.append(i.text.split('\n')[4])
    except NoSuchElementException as e:
        peak_rank.append('_')
        
        
wk=driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]')
for i in wk:
    try:
        weeks.append(i.text.split('\n')[5])
    except NoSuchElementException as e:
        weeks.append('_')

#### 4)Check the length of each:

In [39]:
len(song),len(artist),len(last_week_rank),len(peak_rank),len(weeks)

(100, 100, 100, 100, 100)

#### 5)Creating a Dataframe-

In [41]:
billboard=pd.DataFrame({"Song Name":song,"Artist Name":artist,"Last week Rank":last_week_rank,
                        "Peek Rank":peak_rank,"Weeks":weeks})

pd.set_option('display.max_rows',None)

print('\t'" Data-Analyst Jobs"'\t')
print("*"*100)
billboard

	 Data-Analyst Jobs
****************************************************************************************************

,Song Name,Artist Name,Last week Rank,Peek Rank,Weeks
0,Last Night,Morgan Wallen,5,1,6
1,Flowers,Miley Cyrus,2,1,8
2,Kill Bill,SZA,3,2,13
3,Die For You,The Weeknd & Ariana Grande,1,1,32
4,"Boy's A Liar, Pt. 2",PinkPantheress & Ice Spice,4,3,5
5,Creepin',"Metro Boomin, The Weeknd & 21 Savage",6,3,14
6,Thought You Should Know,Morgan Wallen,13,7,30
7,You Proof,Morgan Wallen,21,5,43
8,NEW,Thinkin' Bout Me,Morgan Wallen,-,9
9,One Thing At A Time,Morgan Wallen,51,10,14
10,NEW,Ain't That Some,Morgan Wallen,-,11
11,Anti-Hero,Taylor Swift,9,1,20
12,NEW,Red Ruby Da Sleeze,Nicki Minaj,-,13
13,Everything I Love,Morgan Wallen,93,14,6
14,NEW,Man Made A Bar,Morgan Wallen Featuring Eric Church,-,15
15,Unholy,Sam Smith & Kim Petras,8,1,24
16,TQG,Karol G x Shakira,7,7,2
17,I Wrote The Book,Morgan Wallen,64,18,6
18,Calm Down,Rema & Selena Gomez,15,15,27
19,Rock And A Hard Place,Bailey Zimmerman,17,16,39
20,I'm Good (Blue),David Guetta & Bebe Rexha,11,4,28
21,Just Wanna Rock,Lil Uzi Vert,12,10,21
22,As It Was,Harry Styles,14,1,49
23,Players,Coi Leray,16,16,10
24,Cuff It,Beyonce,10,6,30
25,Under The Influence,Chris Brown,18,12,26
26,NEW,'98 Braves,Morgan Wallen,-,27
27,Thank God,Kane Brown With Katelyn Brown,19,13,26
28,NEW,Devil Don't Know,Morgan Wallen,-,29
29,NEW,Sunrise,Morgan Wallen,-,30
30,Lavender Haze,Taylor Swift,23,2,20
31,NEW,Born With A Beer In My Hand,Morgan Wallen,-,32
32,Escapism,RAYE Featuring 070 Shake,22,22,14
33,Rich Flex,Drake & 21 Savage,20,2,18
34,NEW,Whiskey Friends,Morgan Wallen,-,35
35,"Going, Going, Gone",Luke Combs,24,23,17
36,Sure Thing,Miguel,28,28,32
37,NEW,Tennessee Numbers,Morgan Wallen,-,38
38,Until I Found You,Stephen Sanchez,27,23,36
39,NEW,Cowgirls,Morgan Wallen Featuring ERNEST,-,40
40,NEW,Hope That's True,Morgan Wallen,-,41
41,Something In The Orange,Zach Bryan,26,10,46
42,NEW,Dying Man,Morgan Wallen,-,43
43,NEW,Keith Whitley,Morgan Wallen,-,44
44,Superhero (Heroes & Villains),"Metro Boomin, Future & Chris Brown",30,8,14
45,Snooze,SZA,32,29,13
46,NEW,In The Bible,Morgan Wallen Featuring HARDY,-,47
47,NEW,Neon Star (Country Boy Lullaby),Morgan Wallen,-,48
48,Golden Hour,JVKE,31,10,28
49,Shirt,SZA,33,11,19
50,NEW,Me + All Your Reasons,Morgan Wallen,-,51
51,NEW,I Deserve A Drink,Morgan Wallen,-,52
52,NEW,F150-50,Morgan Wallen,-,53
53,RE- ENTRY,Tennessee Fan,Morgan Wallen,-,49
54,Heart Like A Truck,Lainey Wilson,29,29,17
55,NEW,Single Than She Was,Morgan Wallen,-,56
56,Made You Look,Meghan Trainor,34,11,20
57,Wait In The Truck,HARDY Featuring Lainey Wilson,40,23,27
58,NEW,Wine Into Water,Morgan Wallen,-,59
59,NEW,On The Street,j-hope With J. Cole,-,60
60,RE- ENTRY,Days That End In Why,Morgan Wallen,-,57
61,Painting Pictures,Superstar Pride,25,25,4
62,NEW,180 (Lifestyle),Morgan Wallen,-,63
63,Bebe Dame,Fuerza Regida X Grupo Frontera,41,25,11
64,NEW,Last Drive Down Main,Morgan Wallen,-,65
65,Bloody Mary,Lady Gaga,46,46,10
66,Favorite Song,Toosii,44,44,3
67,Spin Bout U,Drake & 21 Savage,47,5,18
68,NEW,Good Girl Gone Missin',Morgan Wallen,-,69
69,"Bzrp Music Sessions, Vol. 53",Bizarrap & Shakira,42,9,8
70,NEW,Me To Me,Morgan Wallen,-,71
71,NEW,Money On Me,Morgan Wallen,-,72
72,Nobody Gets Me,SZA,43,10,13
73,Love You Anyway,Luke Combs,39,15,4
74,NEW,Had It,Morgan Wallen,-,75
75,NEW,Outlook,Morgan Wallen,-,76
76,RE- ENTRY,Don't Think Jesus,Morgan Wallen,-,7
77,Special,Lizzo Featuring SZA,53,52,4
78,What He Didn't Do,Carly Pearce,54,53,12
79,Ceilings,Lizzy McAlpine,60,60,3
80,Wild As Her,Corey Kent,58,58,22
81,Watch This (ARIZONATEARS Pluggnb Remix),Lil Uzi Vert,56,56,3
82,Handle On You,Parker McCollum,55,55,10
83,Next Thing You Know,Jordan Davis,67,67,7
84,In Ha Mood,Ice Spice,69,68,5
85,Freestyle,Lil Baby,61,59,23
86,Dawns,Zach Bryan Featuring Maggie Rogers,52,42,6
87,Love Again,The Kid LAROI,59,40,6
88,Private Landing,Don Toliver Featuring Justin Bieber & Future,72,72,2
89,Que Vuelvas,Carin Leon X Grupo Frontera,57,50,11
90,Tennessee Orange,Megan Moroney,70,53,13
91,Low,SZA,63,17,13
92,X Si Volvemos,Karol G x Romeo Santos,48,48,5
93,Trance,"Metro Boomin, Travis Scott & Young Thug",87,42,5
94,Forever,Lil Baby Featuring Fridayy,76,8,9
95,Nonsense,Sabrina Carpenter,75,56,8
96,AMG,"Gabito Ballesteros, Peso Pluma & Natanael Cano",80,66,7
97,Lift Me Up,Rihanna,65,2,19
98,You Didn't,Brett Young,78,63,9
99,10:35,Tiesto Featuring Tate McRae,81,69,7

In [42]:
driver.close()

## Q6. Scrape the details of Highest selling novels.

Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare   .You have to find the following details:
        
A) Book name

B) Author name

C) Volumes sold

D) Publisher

E) Genre

#### 1)Getting the webpage Url.Connect to the driver.

In [2]:
url_tag=('https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare ')

In [3]:
driver=webdriver.Chrome(r"C:\Users\nehas\chromedriver.exe")            
driver.maximize_window()
driver.get(url_tag)

In [ ]:
# Clicking on Open source section-

_tag=driver.find_element(By.XPATH,'')
_tag.click()

#### 2) Make a Empty List of all the data to be scraped.¶

In [4]:
book_name   = []
author_name = []
volume_sold = []
publisher   = []
genre       = []

#### 3) Start scraping data using the given URL

In [5]:
book=driver.find_elements(By.XPATH,'//div[@class="embed block"]/table/tbody/tr/td[2]')
for i in book:
    try:
        book_name.append(i.text)
    except NoSuchElementException as e:
        book_name.append('_')
        
author=driver.find_elements(By.XPATH,'//div[@class="embed block"]/table/tbody/tr/td[3]')
for i in author:
    try:
        author_name.append(i.text)
    except NoSuchElementException as e:
        author_name.append('_')
        
volume=driver.find_elements(By.XPATH,'//div[@class="embed block"]/table/tbody/tr/td[4]')
for i in volume:
    try:
        volume_sold.append(i.text)
    except NoSuchElementException as e:
        volume_sold.append('_')
        
pub=driver.find_elements(By.XPATH,'//div[@class="embed block"]/table/tbody/tr/td[5]')
for i in pub:
    try:
        publisher.append(i.text)
    except NoSuchElementException as e:
        publisher.append('_')
        
gre=driver.find_elements(By.XPATH,'//div[@class="embed block"]/table/tbody/tr/td[6]')
for i in gre:
    try:
        genre.append(i.text)
    except NoSuchElementException as e:
        genre.append('_')

#### 4)Check the length of each:

In [6]:
len(book_name),len(author_name),len(volume_sold),len(publisher),len(genre)

(100, 100, 100, 100, 100)

#### 5)Creating a Dataframe-

In [7]:
bestselling_novel=pd.DataFrame({"Book Name":book_name,"Author Name":author_name,"Volume sold":volume_sold,
                        "Publisher":publisher,"Genre":genre})

pd.set_option('display.max_rows',None)

print('\t'" Top 100 Best Selling Novel"'\t')
print("*"*100)
bestselling_novel

	 Top 100 Best Selling Novel
****************************************************************************************************

,Book Name,Author Name,Volume sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
5,Harry Potter and the Goblet of Fire,"Rowling, J.K.","3,583,215",Bloomsbury,Children's Fiction
6,Harry Potter and the Chamber of Secrets,"Rowling, J.K.","3,484,047",Bloomsbury,Children's Fiction
7,Harry Potter and the Prisoner of Azkaban,"Rowling, J.K.","3,377,906",Bloomsbury,Children's Fiction
8,Angels and Demons,"Brown, Dan","3,193,946",Transworld,"Crime, Thriller & Adventure"
9,Harry Potter and the Half-blood Prince:Childre...,"Rowling, J.K.","2,950,264",Bloomsbury,Children's Fiction
10,Fifty Shades Darker,"James, E. L.","2,479,784",Random House,Romance & Sagas
11,Twilight,"Meyer, Stephenie","2,315,405","Little, Brown Book",Young Adult Fiction
12,"Girl with the Dragon Tattoo,The:Millennium Tri...","Larsson, Stieg","2,233,570",Quercus,"Crime, Thriller & Adventure"
13,Fifty Shades Freed,"James, E. L.","2,193,928",Random House,Romance & Sagas
14,"Lost Symbol,The","Brown, Dan","2,183,031",Transworld,"Crime, Thriller & Adventure"
15,New Moon,"Meyer, Stephenie","2,152,737","Little, Brown Book",Young Adult Fiction
16,Deception Point,"Brown, Dan","2,062,145",Transworld,"Crime, Thriller & Adventure"
17,Eclipse,"Meyer, Stephenie","2,052,876","Little, Brown Book",Young Adult Fiction
18,"Lovely Bones,The","Sebold, Alice","2,005,598",Pan Macmillan,General & Literary Fiction
19,"Curious Incident of the Dog in the Night-time,The","Haddon, Mark","1,979,552",Random House,General & Literary Fiction
20,Digital Fortress,"Brown, Dan","1,928,900",Transworld,"Crime, Thriller & Adventure"
21,"Short History of Nearly Everything,A","Bryson, Bill","1,852,919",Transworld,Popular Science
22,"Girl Who Played with Fire,The:Millennium Trilogy","Larsson, Stieg","1,814,784",Quercus,"Crime, Thriller & Adventure"
23,Breaking Dawn,"Meyer, Stephenie","1,787,118","Little, Brown Book",Young Adult Fiction
24,"Very Hungry Caterpillar,The:The Very Hungry Ca...","Carle, Eric","1,783,535",Penguin,Picture Books
25,"Gruffalo,The","Donaldson, Julia","1,781,269",Pan Macmillan,Picture Books
26,Jamie's 30-Minute Meals,"Oliver, Jamie","1,743,266",Penguin,Food & Drink: General
27,"Kite Runner,The","Hosseini, Khaled","1,629,119",Bloomsbury,General & Literary Fiction
28,One Day,"Nicholls, David","1,616,068",Hodder & Stoughton,General & Literary Fiction
29,"Thousand Splendid Suns,A","Hosseini, Khaled","1,583,992",Bloomsbury,General & Literary Fiction
30,"Girl Who Kicked the Hornets' Nest,The:Millenni...","Larsson, Stieg","1,555,135",Quercus,"Crime, Thriller & Adventure"
31,"Time Traveler's Wife,The","Niffenegger, Audrey","1,546,886",Random House,General & Literary Fiction
32,Atonement,"McEwan, Ian","1,539,428",Random House,General & Literary Fiction
33,Bridget Jones's Diary:A Novel,"Fielding, Helen","1,508,205",Pan Macmillan,General & Literary Fiction
34,"World According to Clarkson,The","Clarkson, Jeremy","1,489,403",Penguin,Humour: Collections & General
35,Captain Corelli's Mandolin,"Bernieres, Louis de","1,352,318",Random House,General & Literary Fiction
36,"Sound of Laughter,The","Kay, Peter","1,310,207",Random House,Autobiography: General
37,Life of Pi,"Martel, Yann","1,310,176",Canongate,General & Literary Fiction
38,Billy Connolly,"Stephenson, Pamela","1,231,957",HarperCollins,Biography: The Arts
39,"Child Called It,A","Pelzer, Dave","1,217,712",Orion,Autobiography: General
40,"Gruffalo's Child,The","Donaldson, Julia","1,208,711",Pan Macmillan,Picture Books
41,Angela's Ashes:A Memoir of a Childhood,"McCourt, Frank","1,204,058",HarperCollins,Autobiography: General
42,Birdsong,"Faulks, Sebastian","1,184,967",Random House,General & Literary Fiction
43,Northern Lights:His Dark Materials S.,"Pullman, Philip","1,181,503",Scholastic Ltd.,Young Adult Fiction
44,Labyrinth,"Mosse, Kate","1,181,093",Orion,General & Literary Fiction
45,Harry Potter and the Half-blood Prince,"Rowling, J.K.","1,153,181",Bloomsbury,Science Fiction & Fantasy
46,"Help,The","Stockett, Kathryn","1,132,336",Penguin,General & Literary Fiction
47,Man and Boy,"Parsons, Tony","1,130,802",HarperCollins,General & Literary Fiction
48,Memoirs of a Geisha,"Golden, Arthur","1,126,337",Random House,General & Literary Fiction
49,"No.1 Ladies' Detective Agency,The:No.1 Ladies'...","McCall Smith, Alexander","1,115,549","Little, Brown Book","Crime, Thriller & Adventure"
50,"Island,The","Hislop, Victoria","1,108,328",Headline,General & Literary Fiction
51,"PS, I Love You","Ahern, Cecelia","1,107,379",HarperCollins,General & Literary Fiction
52,You are What You Eat:The Plan That Will Change...,"McKeith, Gillian","1,104,403",Penguin,Fitness & Diet
53,"Shadow of the Wind,The","Zafon, Carlos Ruiz","1,092,349",Orion,General & Literary Fiction
54,"Tales of Beedle the Bard,The","Rowling, J.K.","1,090,847",Bloomsbury,Children's Fiction
55,"Broker,The","Grisham, John","1,087,262",Random House,"Crime, Thriller & Adventure"
56,"Dr. Atkins' New Diet Revolution:The No-hunger,...","Atkins, Robert C.","1,054,196",Random House,Fitness & Diet
57,"Subtle Knife,The:His Dark Materials S.","Pullman, Philip","1,037,160",Scholastic Ltd.,Young Adult Fiction
58,"Eats, Shoots and Leaves:The Zero Tolerance App...","Truss, Lynne","1,023,688",Profile Books Group,Usage & Writing Guides
59,Delia's How to Cook:(Bk.1),"Smith, Delia","1,015,956",Random House,Food & Drink: General
60,Chocolat,"Harris, Joanne","1,009,873",Transworld,General & Literary Fiction
61,"Boy in the Striped Pyjamas,The","Boyne, John","1,004,414",Random House Childrens Books G,Young Adult Fiction
62,My Sister's Keeper,"Picoult, Jodi","1,003,780",Hodder & Stoughton,General & Literary Fiction
63,"Amber Spyglass,The:His Dark Materials S.","Pullman, Philip","1,002,314",Scholastic Ltd.,Young Adult Fiction
64,To Kill a Mockingbird,"Lee, Harper","998,213",Random House,General & Literary Fiction
65,"Men are from Mars, Women are from Venus:A Prac...","Gray, John","992,846",HarperCollins,Popular Culture & Media: General Interest
66,Dear Fatty,"French, Dawn","986,753",Random House,Autobiography: The Arts
67,"Short History of Tractors in Ukrainian,A","Lewycka, Marina","986,115",Penguin,General & Literary Fiction
68,Hannibal,"Harris, Thomas","970,509",Random House,"Crime, Thriller & Adventure"
69,"Lord of the Rings,The","Tolkien, J. R. R.","967,466",HarperCollins,Science Fiction & Fantasy
70,Stupid White Men:...and Other Sorry Excuses fo...,"Moore, Michael","963,353",Penguin,Current Affairs & Issues
71,"Interpretation of Murder,The","Rubenfeld, Jed","962,515",Headline,"Crime, Thriller & Adventure"
72,Sharon Osbourne Extreme:My Autobiography,"Osbourne, Sharon","959,496","Little, Brown Book",Autobiography: The Arts
73,"Alchemist,The:A Fable About Following Your Dream","Coelho, Paulo","956,114",HarperCollins,General & Literary Fiction
74,At My Mother's Knee ...:and Other Low Joints,"O'Grady, Paul","945,640",Transworld,Autobiography: The Arts
75,Notes from a Small Island,"Bryson, Bill","931,312",Transworld,Travel Writing
76,"Return of the Naked Chef,The","Oliver, Jamie","925,425",Penguin,Food & Drink: General
77,Bridget Jones: The Edge of Reason,"Fielding, Helen","924,695",Pan Macmillan,General & Literary Fiction
78,Jamie's Italy,"Oliver, Jamie","906,968",Penguin,National & Regional Cuisine
79,I Can Make You Thin,"McKenna, Paul","905,086",Transworld,Fitness & Diet
80,Down Under,"Bryson, Bill","890,847",Transworld,Travel Writing
81,"Summons,The","Grisham, John","869,671",Random House,"Crime, Thriller & Adventure"
82,Small Island,"Levy, Andrea","869,659",Headline,General & Literary Fiction
83,Nigella Express,"Lawson, Nigella","862,602",Random House,Food & Drink: General
84,Brick Lane,"Ali, Monica","856,540",Transworld,General & Literary Fiction
85,"Memory Keeper's Daughter,The","Edwards, Kim","845,858",Penguin,General & Literary Fiction
86,Room on the Broom,"Donaldson, Julia","842,535",Pan Macmillan,Picture Books
87,About a Boy,"Hornby, Nick","828,215",Penguin,General & Literary Fiction
88,My Booky Wook,"Brand, Russell","820,563",Hodder & Stoughton,Autobiography: The Arts
89,"God Delusion,The","Dawkins, Richard","816,907",Transworld,Popular Science
90,"""Beano"" Annual,The",0,"816,585",D.C. Thomson,Children's Annuals
91,White Teeth,"Smith, Zadie","815,586",Penguin,General & Literary Fiction
92,"House at Riverton,The","Morton, Kate","814,370",Pan Macmillan,General & Literary Fiction
93,"Book Thief,The","Zusak, Markus","809,641",Transworld,General & Literary Fiction
94,Nights of Rain and Stars,"Binchy, Maeve","808,900",Orion,General & Literary Fiction
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

In [9]:
driver.close()

## Q7. Scrape the details most watched tv series of all time from imdb.com.

Url = https://www.imdb.com/list/ls095964455/.  You have to find the following details:
        
A) Name
B) Year span
C) Genre
D) Run time
E) Ratings
F) Votes

#### 1)Getting the webpage Url(https://www.imdb.com/list/ls095964455/)¶¶
Connect to the driver.

In [18]:
driver=webdriver.Chrome(r"C:\Users\nehas\chromedriver.exe")            
driver.maximize_window()
driver.get('https://www.imdb.com/list/ls095964455/')

#### 2) Make a Empty List of all the data to be scraped.

In [19]:
name       = []
year_span  = []
genre      = []
runtime    = []
rating     = []
votes      = []

#### 3) Start scraping data using the given URL

In [20]:
# Extracting name via Xpath
try:
    nme=driver.find_elements(By.XPATH,'//h3[@class="lister-item-header"]/a')
    for i in nme:
        name.append(i.text)
except NoSuchElementException as e:
    name.append('_')
    
# Extracting YearSpan via Xpath--
try:
    year=driver.find_elements(By.XPATH,'//span[@class="lister-item-year text-muted unbold"]')
    for i in year:
        year_span.append(i.text)
except NoSuchElementException as e:
    year_span.append('_')
    
    
# Extracting genre via Xpath--
try:
    G=driver.find_elements(By.XPATH,'//span[@class="genre"]')
    for i in G:
        genre.append(i.text)
except NoSuchElementException as e:
    genre.append('_')
        
# Extracting runtime via Xpath--
try:
    rt=driver.find_elements(By.XPATH,'//span[@class="runtime"]')
    for i in rt:
        runtime.append(i.text)
except NoSuchElementException as e:
    runtime.append('_')
    
# Extracting rating via Xpath--
try:
    rate=driver.find_elements(By.XPATH,'//div[@class="ipl-rating-star small"]')
    for i in rate:
        rating.append(i.text)
except NoSuchElementException as e:
    rating.append('_')
        
# Extracting Votes via Xpath--
try:
    vote_tag=driver.find_elements(By.XPATH,'//span[@name="nv"]')
    for i in vote_tag:
        votes.append(i.text)
except NoSuchElementException as e:
    votes.append('_')

#### 4)Check the length of each

In [21]:
len(name),len(votes),len(rating),len(runtime),len(genre),len(year_span)

(100, 100, 100, 100, 100, 100)

#### 5)Creating a Dataframe-

In [23]:
IMDB_mostwatched=pd.DataFrame({"Name":name,"Genre":genre,"Runtime":runtime,
                        "year":year_span,"ratings":rating,"votes":votes})

pd.set_option('display.max_rows',None)

print('\t' "IMDB most watched tv series" '\t')
print("*"*90)
IMDB_mostwatched

	IMDB most watched tv series
******************************************************************************************

,Name,Genre,Runtime,year,ratings,votes
0,Game of Thrones,"Action, Adventure, Drama",57 min,(2011–2019),9.2,"2,137,289"
1,Stranger Things,"Drama, Fantasy, Horror",51 min,(2016–2024),8.7,"1,222,365"
2,The Walking Dead,"Drama, Horror, Thriller",44 min,(2010–2022),8.1,"1,014,578"
3,13 Reasons Why,"Drama, Mystery, Thriller",60 min,(2017–2020),7.5,"298,878"
4,The 100,"Drama, Mystery, Sci-Fi",43 min,(2014–2020),7.6,"257,753"
5,Orange Is the New Black,"Comedy, Crime, Drama",59 min,(2013–2019),8.1,"307,104"
6,Riverdale,"Crime, Drama, Mystery",45 min,(2017– ),6.6,"147,174"
7,Grey's Anatomy,"Drama, Romance",41 min,(2005– ),7.6,"316,687"
8,The Flash,"Action, Adventure, Drama",43 min,(2014–2023),7.5,"351,876"
9,Arrow,"Action, Adventure, Crime",42 min,(2012–2020),7.5,"435,375"
10,Money Heist,"Action, Crime, Drama",70 min,(2017–2021),8.2,"488,827"
11,The Big Bang Theory,"Comedy, Romance",22 min,(2007–2019),8.2,"821,383"
12,Black Mirror,"Drama, Mystery, Sci-Fi",60 min,(2011–2019),8.8,"561,623"
13,Sherlock,"Crime, Drama, Mystery",88 min,(2010–2017),9.1,"940,958"
14,Vikings,"Action, Adventure, Drama",44 min,(2013–2020),8.5,"544,857"
15,Pretty Little Liars,"Drama, Mystery, Romance",44 min,(2010–2017),7.4,"170,548"
16,The Vampire Diaries,"Drama, Fantasy, Horror",43 min,(2009–2017),7.7,"327,935"
17,American Horror Story,"Drama, Horror, Sci-Fi",60 min,(2011– ),8,"324,571"
18,Breaking Bad,"Crime, Drama, Thriller",49 min,(2008–2013),9.5,"1,940,230"
19,Lucifer,"Crime, Drama, Fantasy",42 min,(2016–2021),8.1,"331,726"
20,Supernatural,"Drama, Fantasy, Horror",44 min,(2005–2020),8.4,"453,686"
21,Prison Break,"Action, Crime, Drama",44 min,(2005–2017),8.3,"545,708"
22,How to Get Away with Murder,"Crime, Drama, Mystery",43 min,(2014–2020),8.1,"155,557"
23,Teen Wolf,"Action, Drama, Fantasy",41 min,(2011–2017),7.7,"153,921"
24,The Simpsons,"Animation, Comedy",22 min,(1989– ),8.7,"413,739"
25,Once Upon a Time,"Adventure, Fantasy, Romance",60 min,(2011–2018),7.7,"227,870"
26,Narcos,"Biography, Crime, Drama",49 min,(2015–2017),8.8,"433,254"
27,Daredevil,"Action, Crime, Drama",54 min,(2015–2018),8.6,"448,369"
28,Friends,"Comedy, Romance",22 min,(1994–2004),8.9,"1,014,180"
29,How I Met Your Mother,"Comedy, Romance",22 min,(2005–2014),8.3,"694,390"
30,Suits,"Comedy, Drama",44 min,(2011–2019),8.5,"419,292"
31,Mr. Robot,"Crime, Drama, Thriller",49 min,(2015–2019),8.5,"394,421"
32,The Originals,"Drama, Fantasy, Horror",45 min,(2013–2018),8.3,"139,188"
33,Supergirl,"Action, Adventure, Drama",43 min,(2015–2021),6.2,"125,710"
34,Gossip Girl,"Drama, Romance",42 min,(2007–2012),7.5,"178,932"
35,Sense8,"Drama, Mystery, Sci-Fi",60 min,(2015–2018),8.2,"156,761"
36,Gotham,"Action, Crime, Drama",42 min,(2014–2019),7.8,"233,225"
37,Westworld,"Drama, Mystery, Sci-Fi",62 min,(2016–2022),8.5,"512,107"
38,Jessica Jones,"Action, Crime, Drama",56 min,(2015–2019),7.9,"217,707"
39,Modern Family,"Comedy, Drama, Romance",22 min,(2009–2020),8.5,"441,663"
40,Rick and Morty,"Animation, Adventure, Comedy",23 min,(2013– ),9.1,"541,691"
41,Shadowhunters,"Action, Drama, Fantasy",42 min,(2016–2019),6.5,"65,648"
42,The End of the F***ing World,"Adventure, Comedy, Crime",25 min,(2017–2019),8,"198,473"
43,House of Cards,Drama,51 min,(2013–2018),8.7,"510,630"
44,Dark,"Crime, Drama, Mystery",60 min,(2017–2020),8.7,"402,073"
45,Elite,"Crime, Drama, Thriller",60 min,(2018– ),7.3,"82,637"
46,Sex Education,"Comedy, Drama",45 min,(2019– ),8.3,"292,922"
47,Shameless,"Comedy, Drama",46 min,(2011–2021),8.6,"249,383"
48,New Girl,"Comedy, Romance",22 min,(2011–2018),7.8,"230,286"
49,Agents of S.H.I.E.L.D.,"Action, Adventure, Drama",45 min,(2013–2020),7.5,"219,410"
50,You,"Crime, Drama, Romance",45 min,(2018– ),7.7,"264,920"
51,Dexter,"Crime, Drama, Mystery",53 min,(2006–2013),8.7,"733,646"
52,Fear the Walking Dead,"Drama, Horror, Sci-Fi",44 min,(2015–2023),6.8,"133,048"
53,Family Guy,"Animation, Comedy",22 min,(1999– ),8.2,"346,947"
54,The Blacklist,"Crime, Drama, Mystery",43 min,(2013–2023),8,"255,765"
55,Lost,"Adventure, Drama, Fantasy",44 min,(2004–2010),8.3,"562,056"
56,Peaky Blinders,"Crime, Drama",60 min,(2013–2022),8.8,"569,153"
57,House,"Drama, Mystery",44 min,(2004–2012),8.7,"473,303"
58,Quantico,"Crime, Drama, Mystery",42 min,(2015–2018),6.7,"61,754"
59,Orphan Black,"Drama, Sci-Fi, Thriller",44 min,(2013–2017),8.3,"112,600"
60,Homeland,"Crime, Drama, Mystery",55 min,(2011–2020),8.3,"346,651"
61,Blindspot,"Action, Crime, Drama",42 min,(2015–2020),7.3,"75,519"
62,DC's Legends of Tomorrow,"Action, Adventure, Drama",42 min,(2016–2022),6.8,"106,518"
63,The Handmaid's Tale,"Drama, Sci-Fi, Thriller",60 min,(2017– ),8.4,"244,287"
64,Chilling Adventures of Sabrina,"Drama, Fantasy, Horror",60 min,(2018–2020),7.4,"98,871"
65,The Good Doctor,Drama,41 min,(2017– ),8.1,"98,793"
66,Jane the Virgin,Comedy,60 min,(2014–2019),7.9,"52,957"
67,Glee,"Comedy, Drama, Music",44 min,(2009–2015),6.8,"150,587"
68,South Park,"Animation, Comedy",22 min,(1997– ),8.7,"379,218"
69,Brooklyn Nine-Nine,"Comedy, Crime",22 min,(2013–2021),8.4,"326,371"
70,Under the Dome,"Drama, Mystery, Sci-Fi",43 min,(2013–2015),6.5,"108,078"
71,The Umbrella Academy,"Action, Adventure, Comedy",60 min,(2019–2023),7.9,"254,651"
72,True Detective,"Crime, Drama, Mystery",55 min,(2014–2019),8.9,"584,668"
73,The OA,"Drama, Fantasy, Mystery",60 min,(2016–2019),7.8,"107,207"
74,Desperate Housewives,"Comedy, Drama, Mystery",45 min,(2004–2012),7.6,"131,619"
75,Better Call Saul,"Crime, Drama",46 min,(2015–2022),8.9,"556,008"
76,Bates Motel,"Drama, Horror, Mystery",45 min,(2013–2017),8.1,"110,418"
77,The Punisher,"Action, Crime, Drama",53 min,(2017–2019),8.5,"243,269"
78,Atypical,"Comedy, Drama",30 min,(2017–2021),8.2,"93,232"
79,Dynasty,Drama,42 min,(2017–2022),7.3,"23,424"
80,This Is Us,"Comedy, Drama, Romance",45 min,(2016–2022),8.7,"147,738"
81,The Good Place,"Comedy, Drama, Fantasy",22 min,(2016–2020),8.2,"167,386"
82,Iron Fist,"Action, Adventure, Crime",55 min,(2017–2018),6.4,"133,687"
83,The Rain,"Drama, Sci-Fi, Thriller",45 min,(2018–2020),6.3,"38,577"
84,Mindhunter,"Crime, Drama, Mystery",60 min,(2017–2019),8.6,"299,216"
85,Revenge,"Drama, Mystery, Thriller",44 min,(2011–2015),7.8,"121,497"
86,Luke Cage,"Action, Crime, Drama",55 min,(2016–2018),7.3,"133,740"
87,Scandal,"Drama, Thriller",43 min,(2012–2018),7.7,"75,518"
88,The Defenders,"Action, Adventure, Crime",50 min,(2017),7.2,"110,400"
89,Big Little Lies,"Crime, Drama, Mystery",60 min,(2017–2019),8.5,"205,938"
90,Insatiable,"Comedy, Drama, Thriller",45 min,(2018–2019),6.5,"29,974"
91,The Mentalist,"Crime, Drama, Mystery",43 min,(2008–2015),8.1,"188,827"
92,The Crown,"Biography, Drama, History",58 min,(2016–2023),8.6,"227,088"
93,Chernobyl,"Drama, History, Thriller",330 min,(2019),9.4,"781,135"
94,iZombie,"Comedy, Crime, Drama",42 min,(2015–2019),7.8,"70,049"
95,Reign,Drama,42 min,(2013–2017),7.4,"50,997"
96,A Series of Unfortunate Events,"Adventure, Comedy, Drama",50 min,(2017–2019),7.8,"63,004"
97,Criminal Minds,"Crime, Drama, Mystery",42 min,(2005– ),8.1,"204,816"
98,Scream: The TV Series,"Comedy, Crime, Drama",45 min,(2015–2019),7.1,"42,401"
99,The Haunting of Hill House,"Drama, Horror, Mystery",572 min,(2018),8.6,"253,406"

In [25]:
driver.close()

## Q8. Details of Datasetsfrom UCI machine learning repositories. 

Url = https://archive.ics.uci.edu/.   You have to find the following details:
        
A) Dataset name

B) Data type

C) Task

D) Attribute type

E) No of instances

F) No of attribute

G) Year

Note: - from the home page you have to go to the ShowAllDataset page through code.

#### 1)Getting the webpage Url( https://archive.ics.uci.edu/.)¶¶
Connect to the driver.

In [24]:
driver=webdriver.Chrome(r"C:\Users\nehas\chromedriver.exe")            
driver.maximize_window()
driver.get('https://archive.ics.uci.edu/')

In [25]:
show_all=driver.find_element(By.XPATH,'//a[@href="datasets.php"]')
show_all.click()

#### 2) Make a Empty List of all the data to be scraped.

In [26]:
dataset_name    = []
datatype        = []
task            = []
attribute_type  = []
no_of_instances = []
no_of_attribute = []
year            = []

#### 3) Start scraping data using the given URL

In [27]:
# Extracting Dataset name via Xpath
try:
    ds_name=driver.find_elements(By.XPATH,'//p[@class="normal"]/b')
    for i in ds_name:
        dataset_name.append(i.text)
except NoSuchElementException as e:
    dataset_name.append('_')
    
# Extracting Datatype via Xpath--
try:
    dtypes=driver.find_elements(By.XPATH,'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]')
    for i in dtypes:
        datatype.append(i.text)
except NoSuchElementException as e:
    datatype.append('_')
    
    
# Extracting task via Xpath--
try:
    tsk=driver.find_elements(By.XPATH,'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]')
    for i in tsk:
        task.append(i.text)
except NoSuchElementException as e:
    task.append('_')
        
# Extracting attribute type via Xpath--
try:
    attribute_tag=driver.find_elements(By.XPATH,'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]')
    for i in attribute_tag:
        attribute_type.append(i.text)
except NoSuchElementException as e:
    attribute_type.append('_')
    
# Extracting no_of_instance via Xpath--
try:
    no_of_instancetag=driver.find_elements(By.XPATH,'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]')
    for i in no_of_instancetag:
        no_of_instances.append(i.text)
except NoSuchElementException as e:
    no_of_instances.append('_')
        
# Extracting no_of_attribute via Xpath--
try:
    no_attribute_tag=driver.find_elements(By.XPATH,'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]')
    for i in no_attribute_tag:
        no_of_attribute.append(i.text)
except NoSuchElementException as e:
    no_of_attribute.append('_')
        
# Extracting year via Xpath--
try:
    year_tag=driver.find_elements(By.XPATH,'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]/p')
    for i in year_tag:
        year.append(i.text)
except NoSuchElementException as e:
    year.append('_')

#### 4)Check the length of each--

In [28]:
len(dataset_name),len(datatype),len(task),len(attribute_type),len(no_of_attribute),len(no_of_instances),len(year)

(622, 623, 623, 623, 623, 623, 623)

#### 5)Creating a Dataframe-

In [29]:
UCI_respository=pd.DataFrame({"Dataset Name":dataset_name[:622],"Data type":datatype[:622],"Task":task[:622],"Attribute type":attribute_type[:622],
                        "No_of_Attributes":no_of_attribute[:622],"No_of_Instances":no_of_instances[:622],"Year":year[:622]})

print('\t' "UCI_respository" '\t')
print("*"*90)
UCI_respository

	UCI_respository
******************************************************************************************

,Dataset Name,Data type,Task,Attribute type,No_of_Attributes,No_of_Instances,Year
0,Abalone,Data Types,Default Task,Attribute Types,# Attributes,# Instances,Year
1,Adult,Multivariate,Classification,"Categorical, Integer, Real",8,4177,1995
2,Annealing,Multivariate,Classification,"Categorical, Integer",14,48842,1996
3,Anonymous Microsoft Web Data,Multivariate,Classification,"Categorical, Integer, Real",38,798,
4,Arrhythmia,,Recommender-Systems,Categorical,294,37711,1998
...,...,...,...,...,...,...,...
617,Influenza outbreak event prediction via Twitte...,Multivariate,Regression,Integer,11,35040,2020
618,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",525,75840,2020
619,Maternal Health Risk Data Set,Multivariate,Classification,"Integer, Real",50,400,2020
620,Room Occupancy Estimation,,Classification,,7,1014,2020
621,Image Recognition Task Execution Times in Mobi...,"Multivariate, Time-Series",Classification,Real,16,10129,2021

In [32]:
driver.close()

# Q9. Scrape the details of Data science recruiters .

Url = https://www.naukri.com/hr-recruiters-consultants.  You have to find the following details: 
        
A) Name

B) Designation

C)Company 

D)Skills they hire for 

E) Location

Note: - From naukri.com homepage click on the recruiters option and the on the search panel type Data science and 
click on search. All this should be done through code.

#### 1)Getting the webpage Url(https://www.naukri.com/hr-recruiters-consultants)¶¶
Connect to the driver.

In [48]:
driver=webdriver.Chrome(r"C:\Users\nehas\chromedriver.exe")            
driver.maximize_window()
driver.get('https://www.naukri.com/hr-recruiters-consultants')

In [49]:
# Entering Designation as required--

search_tag=driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/div/div[1]/div[1]/div[2]/input')
search_tag.send_keys('Data Science')

In [50]:
# Entering search click as required.

searchbutton=driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/button')
searchbutton.click()

#### 2) Make a Empty List of all the data to be scraped.

In [51]:
Name         = []
designation  = []
company      = []
skills       = []
location     = []

#### 3) Start scraping data using the given URL

In [52]:
# Extracting name via Xpath
try:
    nme_tag=driver.find_elements(By.XPATH,'//a[@class="ellipsis" ]/span')
    for i in nme_tag:
        Name.append(i.text)
except NoSuchElementException as e:
    Name.append('_')
    
    
# Extracting desgination via Xpath--
try:
    desgination_tag=driver.find_elements(By.XPATH,'//span[@class="ellipsis clr"]')
    for i in desgination_tag:
        designation.append(i.text)
except NoSuchElementException as e:
    designation.append('_')
    
    
    
# Extracting Company via Xpath--
try:
    compny_tag=driver.find_elements(By.XPATH,'//p[@class="highlightable"]/a[2]')
    for i in compny_tag:
        company.append(i.text)
except NoSuchElementException as e:
    company.append('_')
    
        
# Extracting Skill via Xpath--
try:
    skl_tag=driver.find_elements(By.XPATH,'//div[@class="hireSec highlightable"]')
    for i in skl_tag:
        skills.append(i.text)
except NoSuchElementException as e:
    skills.append('_')
    
# Extracting Location via Xpath--
try:
    loc_tag=driver.find_elements(By.XPATH,'//p[@class="highlightable"]/span[2]/small')
   
    for i in loc_tag:
        location.append(i.text)
except NoSuchElementException as e:
    location.append('_')

In [53]:
len(location)

49

#### 4)Check the length of each

In [54]:
len(Name),len(designation),len(company),len(skills),len(location)

(50, 50, 50, 50, 49)

#### 5) Creating a Dataframe-

In [62]:
Naukri_jobs = {'Name': Name[:49],'Designation':designation[:49],'Company':company[:49],'Skills they Hire For':skills[:49],'Location':location[:49]}

naukri_jbs = pd.DataFrame(Naukri_jobs)

naukri_jbs

,Name,Designation,Company,Skills they Hire For,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Delhi
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",Hyderabad / Secunderabad
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Pune
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",Ahmedabad
4,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",UK - (london)
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Vadodara / Baroda
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,Chennai
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Trivandrum
8,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",Indore
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage...",Bengaluru / Bangalore
10,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++...",Hyderabad / Secunderabad
11,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ...",Bengaluru / Bangalore
12,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele...",Mumbai
13,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm...",Hyderabad / Secunderabad
14,Priyanka Akiri,HR Manager,Infinitive Software Solutions,"Oracle Dba, Data Science, Data Warehousing, ET...",Hyderabad
15,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",Bhopal
16,Vaishnavi Kudalkar,HR Executive,Codeachive learning,"Data Science, Python, Data Analytics",Mumbai
17,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,"React.js, Data Science, Java, Front End, Busin...",Chandigarh
18,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Pune
19,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re...",Navi Mumbai
20,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Cochin
21,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Softwar...",Delhi
22,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning...",Hyderabad / Secunderabad
23,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee...",Pune
24,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc...",Pune
25,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Pune
26,Deeparchi Sharma,Company Recruiter,ZIGRAM,"Research, Digital Marketing, Analytics, Softwa...",Gurgaon
27,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine...",Pune
28,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product...",Bengaluru / Bangalore
29,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",Bengaluru / Bangalore
30,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne...",Delhi
31,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software...",Bengaluru / Bangalore
32,Dhruv Dev Dubey,Company Recruitment Head,NETAPS FOUNDATION,"Server Administartion, Verilog, Vhdl, Digital ...",Noida
33,Avnish Mishra,Senior Technical &amp; Corporate Recruiter,RMS Risk Management Solutions,"Data Science, Machine Learning, Deep Learning,...",Mysoru / Mysore
34,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",Hyderabad / Secunderabad
35,Avodha,Business Development Associate,Nikitha Palaparthi,"Ethical Hacking, Security Operations Center, S...",Bengaluru / Bangalore
36,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analyti...",New Delhi
37,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat...",Chennai
38,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ...",Aligarh
39,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private...",Salt Lake City
40,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",Pune
41,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark...",Bengaluru / Bangalore
42,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",Mumbai
43,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Indore
44,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B...",Bengaluru / Bangalore
45,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",MYSORE
46,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni...",Hyderabad / Secunderabad
47,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute...",Bengaluru / Bangalore
48,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum...",Mumbai

In [63]:
driver.close()

# *****************COMPLETED********************